(provide 'find_files)


;(find-file (concat *fzl_emacsinitfile_dir*  "/autocomplete_installation.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/autocomplete_installation.sh"))
;(require 'autocomplete_installation)

(find-file (concat *fzl_emacsinitfile_dir*  "/init.el"))
(find-file (concat *fzl_emacsinitfile_dir*  "/init2.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/index.org"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_general_emacs_behaviour.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/buffers_config.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_code_in_general.el"))
(find-file (concat *fzl_emacsinitfile_dir*  "/calendar_config.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_fonts_and_themes.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_code_c_style_for_K_and_RStyle.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_lines_and_columns.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_lines_columns_and_cursor_behaviour.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_minibuffer.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_code_lisp.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/config_code_system.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/fzl_keys.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/org_mode_config.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/fzl_find_file_functions.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/fzl_functions.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/fzl_customization_functions.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/autocomplete_config.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/cedet_config.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/cedet_installation.sh"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/fzl_pkg_install_functions.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/speedbar_config.el"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/magit_installation.sh"))
;(find-file (concat *fzl_emacsinitfile_dir*  "/xml_mode.el"))
