#+Title:emacsinitfile
#+Subtitle: yet another (emacs customization)


* Básico do emacs

** instalação dos laguages servers provides - lsp

#+name: 
#+begin_src shell
  sudo npm install @angular/language-server
#+end_src



** Fatures (Facilidades desta configuração)

*** Shortcuts
| teclas                 | Descrição                                                  | fonte     |
| C-c f o                | Mostra list Arqs e Dirs especiais pra ficar fácil de abrir | fzl-emacs |
| C-h w RET nomedafuncao | Mostra qual shortcut esta associado à função               | emacs     |
|                        |                                                            |           |

*** Mostra list Arqs e Dirs especiais pra ficar fácil de abrir
C-c f o
Vc configura caminhos de aquivos e diretorios que vc abre muito
frequentemente e fica fácil reabri-los novamente

**** Consulta qual tecla de atalho está associada e qual função
   C-h w RET nomedafuncao

So I divided the work in branchs.

* basic-config
  I think is the most common configuration. Basic it is a defaults sanitize

* basic-developer-config
  To edit most common developer language

* full customization

  The goal is combine features of previos configuration.
    
  My dreamed final goal is to support my own BPMS project.

  With several fantastic peace of software together like nexus, maven, eclipse and some framework the main intent is to provide a bpms plataform to develope softwares.


