# -*- mode: restclient; eval: (setq restclient-vars-alist '((:authKey. (getenv "GITHUB_AUTH_TOKEN")))) -*-

#https://docs.github.com/pt/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#deployments
#https://docs.github.com/pt/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#statuses
#https://docs.github.com/pt/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#codespaces-lifecycle-admin
#https://docs.github.com/pt/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#codespaces


# globar vars
:github = https://api.github.com
:authKey = eval:(getenv "GITHUB_AUTH_TOKEN")
:user_name = wagnermarques

# spaces & urls
:user_followers = :github/users/:user_name/followers


### Get user information
GET :github/users/:user_name
Accept: application/vnd.github.v3+json
User-Agent: :user_name


### Get user followers
GET :user_followers
Accept: application/vnd.github.v3+json
User-Agent: :user_name



# repos
# the fine grained key needs respo status permission
# fzl-github-branch-count
# fzl-github-branch-list
# fzl-github-branch-update

### Get to Check if specific branch had new pushes in a specific branch
# fzl-check-branch-update
:repo_emacsinitfile = emacsinitfile
:branch_name = trunk-basic-config

GET :github/repos/:user_name/:repo_emacsinitfile/branches/:branch_name
Authorization: Bearer :authKey
User-Agent: :user_name

### Get to Check if specific branch had new pushes in a specific branch
GET https://:authKey
